<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'chillerlan/php-qrcode' => array(
            'pretty_version' => '3.4.1',
            'version' => '3.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chillerlan/php-qrcode',
            'aliases' => array(),
            'reference' => '468603b687a5fe75c1ff33857a45f1726c7b95a9',
            'dev_requirement' => false,
        ),
        'chillerlan/php-settings-container' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chillerlan/php-settings-container',
            'aliases' => array(),
            'reference' => 'd1b5284d6eb3a767459738bb0b20073f0cb3eeaf',
            'dev_requirement' => false,
        ),
        'mobiledetect/mobiledetectlib' => array(
            'pretty_version' => '2.8.41',
            'version' => '2.8.41.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mobiledetect/mobiledetectlib',
            'aliases' => array(),
            'reference' => 'fc9cccd4d3706d5a7537b562b59cc18f9e4c0cb1',
            'dev_requirement' => false,
        ),
        'paymentwall/paymentwall-php' => array(
            'pretty_version' => '2.2.3',
            'version' => '2.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paymentwall/paymentwall-php',
            'aliases' => array(),
            'reference' => '040cbd3aecafe25af35568590f78b6cef4b72015',
            'dev_requirement' => false,
        ),
        'piggly/php-pix' => array(
            'pretty_version' => '1.2.8',
            'version' => '1.2.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../piggly/php-pix',
            'aliases' => array(),
            'reference' => '0d45caa94188f18dd0a00b73bf6efcb611d408d4',
            'dev_requirement' => false,
        ),
        'stripe/stripe-php' => array(
            'pretty_version' => 'v12.1.0',
            'version' => '12.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stripe/stripe-php',
            'aliases' => array(),
            'reference' => '8ef18513811e3ad0cac50f699deac4032409ae07',
            'dev_requirement' => false,
        ),
    ),
);
